# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5e_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Rev12
    - Rev13
    - Rev14
    - Rev15
    - Rev16
    - Rev17
    - Rev26
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5e_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Rev12
      - Rev13
      - Rev14
      - Rev15
      - Rev16
      - Rev17
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      Rev26
gripper_effort_controller:
  type: effort_controllers/JointEffortController
  joints:
    Rev26
  gains:
    Rev26:
      p: 100
      d: 1
      i: 1
      i_clamp: 1